// Code generated by cmd/ossiegen from Apache Ossie core-spec/osi-schema.json; DO NOT EDIT.
// Derived from Apache Ossie at 88e0011148283302c9a04cd0287e00e0b9d87354; see NOTICE and licenses/ossie/.
// SPDX-License-Identifier: Apache-2.0
// Ossie spec version: 0.2.0.dev0
package ossie

const SupportedSpecVersion = "0.2.0.dev0"

type Document struct {
	SemanticModel    []SemanticModel  `yaml:"semantic_model" json:"semantic_model"`
	Version          string           `yaml:"version" json:"version"`
	Name             string           `yaml:"name,omitempty" json:"name,omitempty"`
	Description      string           `yaml:"description,omitempty" json:"description,omitempty"`
	Requires         []string         `yaml:"requires,omitempty" json:"requires,omitempty"`
	Ontology         []map[string]any `yaml:"ontology,omitempty" json:"ontology,omitempty"`
	OntologyMappings []map[string]any `yaml:"ontology_mappings,omitempty" json:"ontology_mappings,omitempty"`
}

type AIContext = any

type CustomExtension struct {
	Data       string `yaml:"data" json:"data"`
	VendorName Vendor `yaml:"vendor_name" json:"vendor_name"`
}

type DataType string

const (
	DataTypeString     DataType = "String"
	DataTypeInteger    DataType = "Integer"
	DataTypeDecimal    DataType = "Decimal"
	DataTypeFloat      DataType = "Float"
	DataTypeBoolean    DataType = "Boolean"
	DataTypeDate       DataType = "Date"
	DataTypeTime       DataType = "Time"
	DataTypeDateTime   DataType = "DateTime"
	DataTypeDateTimeTz DataType = "DateTimeTz"
	DataTypeOpaque     DataType = "Opaque"
)

type Dataset struct {
	AIContext        AIContext         `yaml:"ai_context,omitempty" json:"ai_context,omitempty"`
	CustomExtensions []CustomExtension `yaml:"custom_extensions,omitempty" json:"custom_extensions,omitempty"`
	Description      string            `yaml:"description,omitempty" json:"description,omitempty"`
	Fields           []Field           `yaml:"fields,omitempty" json:"fields,omitempty"`
	Name             string            `yaml:"name" json:"name"`
	PrimaryKey       []string          `yaml:"primary_key,omitempty" json:"primary_key,omitempty"`
	Source           string            `yaml:"source" json:"source"`
	UniqueKeys       [][]string        `yaml:"unique_keys,omitempty" json:"unique_keys,omitempty"`
}

type Dialect string

const (
	DialectANSISQL    Dialect = "ANSI_SQL"
	DialectSnowflake  Dialect = "SNOWFLAKE"
	DialectMDX        Dialect = "MDX"
	DialectTableau    Dialect = "TABLEAU"
	DialectDatabricks Dialect = "DATABRICKS"
	DialectMAQL       Dialect = "MAQL"
	DialectBigQuery   Dialect = "BIGQUERY"
)

type DialectExpression struct {
	Dialect    Dialect `yaml:"dialect" json:"dialect"`
	Expression string  `yaml:"expression" json:"expression"`
}

type Dimension struct {
	IsTime *bool `yaml:"is_time,omitempty" json:"is_time,omitempty"`
}

type Expression struct {
	Dialects []DialectExpression `yaml:"dialects" json:"dialects"`
}

type Field struct {
	AIContext        AIContext         `yaml:"ai_context,omitempty" json:"ai_context,omitempty"`
	CustomExtensions []CustomExtension `yaml:"custom_extensions,omitempty" json:"custom_extensions,omitempty"`
	Datatype         DataType          `yaml:"datatype,omitempty" json:"datatype,omitempty"`
	Description      string            `yaml:"description,omitempty" json:"description,omitempty"`
	Dimension        *Dimension        `yaml:"dimension,omitempty" json:"dimension,omitempty"`
	Expression       Expression        `yaml:"expression" json:"expression"`
	Label            string            `yaml:"label,omitempty" json:"label,omitempty"`
	Name             string            `yaml:"name" json:"name"`
}

type Metric struct {
	AIContext        AIContext         `yaml:"ai_context,omitempty" json:"ai_context,omitempty"`
	CustomExtensions []CustomExtension `yaml:"custom_extensions,omitempty" json:"custom_extensions,omitempty"`
	Datatype         DataType          `yaml:"datatype,omitempty" json:"datatype,omitempty"`
	Description      string            `yaml:"description,omitempty" json:"description,omitempty"`
	Expression       Expression        `yaml:"expression" json:"expression"`
	Name             string            `yaml:"name" json:"name"`
}

type Relationship struct {
	AIContext        AIContext         `yaml:"ai_context,omitempty" json:"ai_context,omitempty"`
	CustomExtensions []CustomExtension `yaml:"custom_extensions,omitempty" json:"custom_extensions,omitempty"`
	From             string            `yaml:"from" json:"from"`
	FromColumns      []string          `yaml:"from_columns" json:"from_columns"`
	Name             string            `yaml:"name" json:"name"`
	To               string            `yaml:"to" json:"to"`
	ToColumns        []string          `yaml:"to_columns" json:"to_columns"`
}

type SemanticModel struct {
	AIContext        AIContext         `yaml:"ai_context,omitempty" json:"ai_context,omitempty"`
	CustomExtensions []CustomExtension `yaml:"custom_extensions,omitempty" json:"custom_extensions,omitempty"`
	Datasets         []Dataset         `yaml:"datasets" json:"datasets"`
	Description      string            `yaml:"description,omitempty" json:"description,omitempty"`
	Metrics          []Metric          `yaml:"metrics,omitempty" json:"metrics,omitempty"`
	Name             string            `yaml:"name" json:"name"`
	Relationships    []Relationship    `yaml:"relationships,omitempty" json:"relationships,omitempty"`
}

type Vendor string
