package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type schema struct {
	Type       string            `json:"type"`
	Const      string            `json:"const"`
	Ref        string            `json:"$ref"`
	Enum       []string          `json:"enum"`
	OneOf      []schema          `json:"oneOf"`
	Properties map[string]schema `json:"properties"`
	Required   []string          `json:"required"`
	Items      *schema           `json:"items"`
	Defs       map[string]schema `json:"$defs"`
}

func main() {
	in := flag.String("schema", "ossie/schema/osi-schema.json", "Apache Ossie JSON schema")
	out := flag.String("out", "ossie/model.go", "generated Go binding")
	upstreamRevision := flag.String("upstream-revision", "88e0011148283302c9a04cd0287e00e0b9d87354", "Apache Ossie source revision recorded in the generated header")
	flag.Parse()

	b, err := os.ReadFile(*in)
	must(err)
	var root schema
	must(json.Unmarshal(b, &root))
	version, ok := root.Properties["version"]
	if !ok || version.Const == "" {
		panic("schema does not define a constant version")
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by cmd/ossiegen from Apache Ossie core-spec/osi-schema.json; DO NOT EDIT.")
	fmt.Fprintf(&buf, "// Derived from Apache Ossie at %s; see NOTICE and licenses/ossie/.\n", *upstreamRevision)
	fmt.Fprintln(&buf, "// SPDX-License-Identifier: Apache-2.0")
	fmt.Fprintf(&buf, "// Ossie spec version: %s\npackage ossie\n\n", version.Const)
	fmt.Fprintf(&buf, "const SupportedSpecVersion = %q\n\n", version.Const)

	emitObject(&buf, "Document", root, root)

	names := make([]string, 0, len(root.Defs))
	for name := range root.Defs {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		d := root.Defs[name]
		switch {
		case len(d.Enum) > 0:
			emitEnum(&buf, name, d.Enum)
		case len(d.OneOf) > 0:
			fmt.Fprintf(&buf, "type %s = any\n\n", name)
		case d.Type == "string":
			fmt.Fprintf(&buf, "type %s string\n\n", name)
		case d.Type == "object":
			emitObject(&buf, name, d, root)
		default:
			panic("unsupported definition: " + name)
		}
	}

	formatted, err := format.Source(buf.Bytes())
	must(err)
	must(os.WriteFile(*out, formatted, 0o644))
}

func emitObject(buf *bytes.Buffer, name string, s schema, root schema) {
	required := map[string]bool{}
	for _, k := range s.Required {
		required[k] = true
	}
	keys := make([]string, 0, len(s.Properties))
	for k := range s.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	fmt.Fprintf(buf, "type %s struct {\n", name)
	for _, key := range keys {
		p := s.Properties[key]
		goType := typeFor(p, root, required[key])
		tag := key
		if !required[key] {
			tag += ",omitempty"
		}
		fmt.Fprintf(buf, "\t%s %s `yaml:%q json:%q`\n", goName(key), goType, tag, tag)
	}
	if name == "Document" {
		// Apache Ossie's official examples may use the ontology envelope in
		// addition to Core semantic_model documents. These fields are preserved
		// losslessly as metadata; Metis does not interpret them during SQL
		// compilation yet.
		fmt.Fprintln(buf, "\tName string `yaml:\"name,omitempty\" json:\"name,omitempty\"`")
		fmt.Fprintln(buf, "\tDescription string `yaml:\"description,omitempty\" json:\"description,omitempty\"`")
		fmt.Fprintln(buf, "\tRequires []string `yaml:\"requires,omitempty\" json:\"requires,omitempty\"`")
		fmt.Fprintln(buf, "\tOntology []map[string]any `yaml:\"ontology,omitempty\" json:\"ontology,omitempty\"`")
		fmt.Fprintln(buf, "\tOntologyMappings []map[string]any `yaml:\"ontology_mappings,omitempty\" json:\"ontology_mappings,omitempty\"`")
	}
	fmt.Fprintln(buf, "}")
	fmt.Fprintln(buf)
}

func typeFor(s schema, root schema, required bool) string {
	if s.Ref != "" {
		name := s.Ref[strings.LastIndex(s.Ref, "/")+1:]
		if !required && root.Defs[name].Type == "object" {
			return "*" + name
		}
		return name
	}
	if len(s.OneOf) > 0 {
		return "any"
	}
	switch s.Type {
	case "string":
		return "string"
	case "boolean":
		if required {
			return "bool"
		}
		return "*bool"
	case "array":
		if s.Items == nil {
			return "[]any"
		}
		return "[]" + typeFor(*s.Items, root, true)
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

func emitEnum(buf *bytes.Buffer, name string, values []string) {
	fmt.Fprintf(buf, "type %s string\n\nconst (\n", name)
	for _, v := range values {
		fmt.Fprintf(buf, "\t%s%s %s = %q\n", name, enumName(v), name, v)
	}
	fmt.Fprintln(buf, ")")
	fmt.Fprintln(buf)
}

func goName(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == ' ' })
	for i, p := range parts {
		if p != "" {
			parts[i] = goToken(p)
		}
	}
	return strings.Join(parts, "")
}

func goToken(s string) string {
	switch strings.ToLower(s) {
	case "ai":
		return "AI"
	case "id":
		return "ID"
	case "sql":
		return "SQL"
	case "url":
		return "URL"
	case "http":
		return "HTTP"
	case "json":
		return "JSON"
	case "api":
		return "API"
	default:
		return strings.ToUpper(s[:1]) + s[1:]
	}
}

func enumName(s string) string {
	if strings.Contains(s, "_") {
		parts := strings.Split(s, "_")
		for i, p := range parts {
			parts[i] = enumToken(p)
		}
		return strings.Join(parts, "")
	}
	if s == strings.ToUpper(s) {
		return enumToken(s)
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func enumToken(s string) string {
	switch s {
	case "ANSI", "SQL", "MDX", "MAQL":
		return s
	case "BIGQUERY":
		return "BigQuery"
	default:
		lower := strings.ToLower(s)
		return strings.ToUpper(lower[:1]) + lower[1:]
	}
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
